/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author WINDOWS 10
 */
public class FrameIdealTubuh extends javax.swing.JFrame {

    /**
     * Creates new form FrameIdealTubuh
     */
    public FrameIdealTubuh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jeniskelamin = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idnama = new javax.swing.JTextField();
        idtinggi = new javax.swing.JTextField();
        idberat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rdblaki = new javax.swing.JRadioButton();
        rdbperempuan = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        buttonhitung = new javax.swing.JButton();
        buttoncobaulang = new javax.swing.JButton();
        buttonkeluar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        idideal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        idhasil = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        idsaran = new javax.swing.JTextField();

        jTextField6.setText("?");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Aplikasi Cek Ideal Tubuh");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 10, 290, 34);

        jLabel2.setText("Nama");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(23, 64, 70, 14);

        jLabel3.setText("Tinggi");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(23, 102, 80, 14);

        jLabel4.setText("Berat");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(23, 140, 90, 14);
        jPanel1.add(idnama);
        idnama.setBounds(124, 61, 181, 30);
        jPanel1.add(idtinggi);
        idtinggi.setBounds(124, 99, 154, 30);
        jPanel1.add(idberat);
        idberat.setBounds(124, 137, 154, 30);

        jLabel5.setText("Jenis kelamin");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(23, 179, 90, 14);

        jeniskelamin.add(rdblaki);
        rdblaki.setText("Laki-laki");
        rdblaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdblakiActionPerformed(evt);
            }
        });
        jPanel1.add(rdblaki);
        rdblaki.setBounds(124, 175, 80, 23);

        jeniskelamin.add(rdbperempuan);
        rdbperempuan.setText("Perempuan");
        jPanel1.add(rdbperempuan);
        rdbperempuan.setBounds(211, 175, 100, 23);

        jLabel6.setText("cm");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(290, 110, 40, 14);

        jLabel7.setText("kg");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(290, 150, 30, 14);

        buttonhitung.setText("Hitung");
        buttonhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonhitungActionPerformed(evt);
            }
        });
        jPanel1.add(buttonhitung);
        buttonhitung.setBounds(110, 210, 80, 30);

        buttoncobaulang.setText("Coba Ulang");
        buttoncobaulang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoncobaulangActionPerformed(evt);
            }
        });
        jPanel1.add(buttoncobaulang);
        buttoncobaulang.setBounds(220, 210, 100, 30);

        buttonkeluar.setText("Keluar");
        buttonkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonkeluarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonkeluar);
        buttonkeluar.setBounds(140, 390, 80, 30);

        jLabel8.setText("Berat Badan Ideal Anda Adalah ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(23, 253, 180, 20);

        idideal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ididealActionPerformed(evt);
            }
        });
        jPanel1.add(idideal);
        idideal.setBounds(200, 250, 79, 30);

        jLabel9.setText("kg");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(290, 260, 30, 14);

        idhasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idhasilActionPerformed(evt);
            }
        });
        jPanel1.add(idhasil);
        idhasil.setBounds(20, 307, 338, 30);

        jLabel10.setText("Hasil Analisa Kesehatan");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 287, 170, 14);

        idsaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idsaranActionPerformed(evt);
            }
        });
        jPanel1.add(idsaran);
        idsaran.setBounds(20, 350, 338, 28);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 430, 440);

        setSize(new java.awt.Dimension(395, 481));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rdblakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdblakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdblakiActionPerformed

    private void buttoncobaulangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoncobaulangActionPerformed
        // TODO add your handling code here:
        idnama.setText("");
        idberat.setText("");
        idtinggi.setText("");
        idideal.setText("");
        idhasil.setText("");
        idsaran.setText("");
        jeniskelamin.clearSelection();
        
    }//GEN-LAST:event_buttoncobaulangActionPerformed

    private void ididealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ididealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ididealActionPerformed

    private void buttonkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonkeluarActionPerformed
        // TODO add your handling code here:
        dispose();
        System.exit(0);
        
    }//GEN-LAST:event_buttonkeluarActionPerformed

    private void buttonhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonhitungActionPerformed
        // TODO add your handling code here:
        double t = Double.valueOf(idtinggi.getText());
        double b = Double.valueOf(idberat.getText());  
        double h = 0;
        String nama = idnama.getText();
        
        if(rdblaki.isSelected()){
            h = (t-100);
        }else if (rdbperempuan.isSelected()){
            h = (t-104);                   
        }
        
        String temp = Double.toString(h);
        
        if(h<b){
            idideal.setText(temp);
            idhasil.setText("Maaf"+nama+"Sepertinya Anda Overweight");
            idsaran.setText("Sepertiya Anda Harus Diet");
            
        }
        else if(h>b){
            idideal.setText(temp);
            idhasil.setText("Maaf" +nama+ "Sepertinya Anda Underweight");
            idsaran.setText("Sepertiya Anda Harus Banyak Makan");
        }else{
            idideal.setText(temp);
            idhasil.setText("Tubuh Anda Ideal");
            idsaran.setText("Pertahankan");}
        
    }//GEN-LAST:event_buttonhitungActionPerformed

    private void idhasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idhasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idhasilActionPerformed

    private void idsaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idsaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idsaranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameIdealTubuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameIdealTubuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameIdealTubuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameIdealTubuh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameIdealTubuh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttoncobaulang;
    private javax.swing.JButton buttonhitung;
    private javax.swing.JButton buttonkeluar;
    private javax.swing.JTextField idberat;
    private javax.swing.JTextField idhasil;
    private javax.swing.JTextField idideal;
    private javax.swing.JTextField idnama;
    private javax.swing.JTextField idsaran;
    private javax.swing.JTextField idtinggi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.ButtonGroup jeniskelamin;
    private javax.swing.JRadioButton rdblaki;
    private javax.swing.JRadioButton rdbperempuan;
    // End of variables declaration//GEN-END:variables
}
